src/objects/Fielo_ItemVenta__c.object
<CustomObject>
    <fields>
        <fullName>F_IdProducto__c</fullName>
        <label>Id Producto</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_Venta__c</fullName>
        <label>Venta</label>
        <referenceTo>Fielo_Venta__c</referenceTo>
        <relationshipLabel>Itens de Venda</relationshipLabel>
        <relationshipName>Itens_de_Venda</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Item Venta</label>
    <nameField>
        <displayFormat>IV-{0000000000}</displayFormat>
        <label># Item Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fielo_VariablesFraude__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de las variables utilizadas para el control de Fraudes de Acumulación Club Terpel</description>
    <fields>
        <fullName>F_CodigosCombustibleCorriente__c</fullName>
        <description>Códigos de Productos correspondientes a Combustible Corriente separados por coma</description>
        <inlineHelpText>Códigos de Productos correspondientes a Combustible Corriente separados por coma</inlineHelpText>
        <label>Códigos Combustible Corriente</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_CodigosCombustibleDiesel__c</fullName>
        <description>Códigos de Productos correspondientes a Combustible Diesel separados por coma</description>
        <inlineHelpText>Códigos de Productos correspondientes a Combustible Diesel separados por coma</inlineHelpText>
        <label>Códigos Combustible Diesel</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_CodigosCombustibleExtra__c</fullName>
        <description>Códigos de Productos correspondientes a Combustible Extra separados por coma</description>
        <inlineHelpText>Códigos de Productos correspondientes a Combustible Extra separados por coma</inlineHelpText>
        <label>Códigos Combustible Extra</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Fielo - Variables de Fraude</label>
</CustomObject>

src/objects/Fielo_Venta__c.object
<CustomObject>
    <fields>
        <fullName>F_OrigenVenta__c</fullName>
        <label>Origen Venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Estación de Servicio</fullName>
                </value>
                <value>
                    <fullName>Tienda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_TipoCombustible__c</fullName>
        <label>Tipo de Combustible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corriente</fullName>
                </value>
                <value>
                    <fullName>Diesel</fullName>
                </value>
                <value>
                    <fullName>Extra</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Venta</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Numero Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Fielo_TRIG_ItemVentaAfter.cls
/*******************************************************************************
*                          Copyright (C) 2017 ValueNET
* ------------------------------------------------------------------------------
* Author: EBC                          date: 31/05/2017
* 
* Name: Fielo_TRIG_ItemVentaAfter.cls
* 
* Class for after event of Fielo Item Venta
*
*******************************************************************************/
public with sharing class Fielo_TRIG_ItemVentaAfter {

	// Origin Venta
	public final static String ESTACION_DE_SERVICIO = 'Estación de Servicio';

	// Constants
	public final static String EXTRA = 'Extra';
	public final static String DIESEL = 'Diesel';
	public final static String CORRIENTE = 'Corriente';

	// Custom Settings for Variables Fraude
	private static final Fielo_VariablesFraude__c VARIABLES_FRAUDE = 
				Fielo_VariablesFraude__c.getInstance('Fielo - Club Terpel');

    private static final Set<String> fCombCorriente = new Set<String>(
    			VARIABLES_FRAUDE.F_CodigosCombustibleCorriente__c.split(','));
    private static final Set<String> fCombExtra = new Set<String>(
    			VARIABLES_FRAUDE.F_CodigosCombustibleExtra__c.split(','));
    private static final Set<String> fCombDiesel = new Set<String>(
    			VARIABLES_FRAUDE.F_CodigosCombustibleDiesel__c.split(',')); 

	public static void tipoCombustible() {

		TriggerCheck.assert();

		Set<id> lIdVentaSet = new Set<id>();
		for(Fielo_ItemVenta__c ivt :(List<Fielo_ItemVenta__c>) trigger.new) {

			lIdVentaSet.add(ivt.F_Venta__c);
		}

		Map<Id,Fielo_Venta__c> lVentaMap = new Map<Id,Fielo_Venta__c>([
												SELECT F_OrigenVenta__c
												FROM Fielo_Venta__c 
												WHERE id IN :lIdVentaSet
												AND F_OrigenVenta__c = :ESTACION_DE_SERVICIO]);
		
		List<Fielo_Venta__c> lVentaLst = new List<Fielo_Venta__c>();
		for(Fielo_ItemVenta__c ivt :(List<Fielo_ItemVenta__c>) trigger.new) {

			Fielo_Venta__c lVentaAux = lVentaMap.get(ivt.F_Venta__c);
			if(lVentaAux != null) {

				if(fCombCorriente.contains(ivt.F_IdProducto__c)) {

					lVentaAux.F_TipoCombustible__c = CORRIENTE;
					lVentaLst.add(lVentaAux);
				}
				else if(fCombExtra.contains(ivt.F_IdProducto__c)) {

					lVentaAux.F_TipoCombustible__c = EXTRA;
					lVentaLst.add(lVentaAux);
				}
				else if(fCombDiesel.contains(ivt.F_IdProducto__c)) {

					lVentaAux.F_TipoCombustible__c = DIESEL;
					lVentaLst.add(lVentaAux);
				}
			}
		}

		if(!lVentaLst.isEmpty()) update lVentaLst;
	}
}