src/objects/Fielo_ParametrosLifeMiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parámetros de las integraciones de LifeMiles</description>
    <label>Fielo - Parámetros LifeMiles</label>
</CustomObject>

src/objects/Fielo_RedirectURLs_ClubTerpel__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Fielo - Redirect URLs Club Terpel</label>
</CustomObject>

src/objects/Fielo_VariablesFraude__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de las variables utilizadas para el control de Fraudes de Acumulación Club Terpel</description>
    <label>Fielo - Variables de Fraude</label>
</CustomObject>

src/objects/Ter_Codigos_Errores__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Códigos Errores</label>
</CustomObject>

src/objects/Ter_Homologacion_Listas__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuración personalizada para homologar los valores de las listas que lleguen en las integraciones</description>
    <label>Homologacion Listas</label>
</CustomObject>

src/objects/Ter_Negocio_Complementario__c.object
<CustomObject>
    <description>Este objeto contiene los registros de los negocios complementarios de las estaciones de servicio de Terpel.</description>
    <fields>
        <fullName>Ter_Codigo_DIAN__c</fullName>
        <description>Código de la DIAN asignado al negocio complementario.</description>
        <label>Código DIAN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ter_Usuario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usuario</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Negocios_Complementarios</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Negocio Complementario</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Negocios Complementarios</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Ter_POS__c.object
<CustomObject>
    <fields>
        <fullName>Ter_Codigo_DIAN__c</fullName>
        <label>Código DIAN</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ter_Negocio_Complementario__c</fullName>
        <label>Negocio Complementario</label>
        <referenceTo>Ter_Negocio_Complementario__c</referenceTo>
        <relationshipLabel>POS</relationshipLabel>
        <relationshipName>Ter_POS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ter_Usuario__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usuario</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Ter_POS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>POS</label>
    <nameField>
        <label>Nombre POS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ter_POS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Ter_TDC_Valor_Milla__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Ter_TDC_Valor_Milla__c</fullName>
        <description>Valor de la milla</description>
        <label>Valor milla</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Valor milla</label>
</CustomObject>

src/classes/Ter_TDC_Home_tst.cls
@isTest
private class Ter_TDC_Home_tst {
	
	@isTest static void testValidarClienteLifeMiles() {

		Test.startTest();
			Account objCuenta = Ter_DataGenerator_cls.crearCuenta(true);
			FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('1245377192154','88556699','T100000000012', null);
			FieloPLT__Program__c objProgram = Ter_DataGenerator_cls.generateProgramFielo();
			insert  objProgram;

			objMember.FieloPLT__Program__c = objProgram.Id;
			Contact objContact = Ter_DataGenerator_cls.generateContact();
			objContact.AccountId = objCuenta.Id;
			insert objContact;

			objMember.FieloPLT__Contact__c = objContact.Id;
			insert objMember;

			Ter_Negocio_Complementario__c objTienda = Ter_DataGenerator_cls.crearTTCC(false);
			insert objTienda;

			Ter_POS__c objPos = new Ter_POS__c();
			objPos.Ter_Usuario__c = UserInfo.getUserId();
			objPos.Name = 'Nombre POS';
			objPos.Ter_Codigo_DIAN__c = 'AVX';
			objPos.Ter_Negocio_Complementario__c = objTienda.Id;
			insert objPos;


			Ter_TDC_Home_Ctr.TDC_Wrapper objResult = Ter_TDC_Home_Ctr.validarCliente('NLM','1245377192154');
		
			System.assertEquals(false, objResult.blnError);
			System.assertNotEquals(null, objResult.idMemberId);
			System.assertNotEquals(null, objResult.strNumeroDocumento);
			System.assertEquals('1245377192154', objResult.strNombre);
		Test.stopTest();
	}
	
	@isTest static void testValidarClienteTarjetaPreinscrita() {
		Test.startTest();
			Account objCuenta = Ter_DataGenerator_cls.crearCuenta(true);
			FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('1245377192154','88556699','T100000000012', null);
			FieloPLT__Program__c objProgram = Ter_DataGenerator_cls.generateProgramFielo();
			insert  objProgram;

			objMember.FieloPLT__Program__c = objProgram.Id;
			Contact objContact = Ter_DataGenerator_cls.generateContact();
			objContact.AccountId = objCuenta.Id;
			insert objContact;

			objMember.FieloPLT__Contact__c = objContact.Id;
			insert objMember;

			Ter_Negocio_Complementario__c objTienda = Ter_DataGenerator_cls.crearTTCC(false);
			insert objTienda;

			Ter_POS__c objPos = new Ter_POS__c();
			objPos.Ter_Usuario__c = UserInfo.getUserId();
			objPos.Name = 'Nombre POS';
			objPos.Ter_Codigo_DIAN__c = 'AVX';
			objPos.Ter_Negocio_Complementario__c = objTienda.Id;
			insert objPos;

			Ter_TDC_Home_Ctr.TDC_Wrapper objResult = Ter_TDC_Home_Ctr.validarCliente('TPI','T100000000012');
		
			System.assertEquals(objResult.blnError, false);
			System.assertNotEquals(objResult.idMemberId, null);
			System.assertNotEquals(objResult.strNumeroDocumento, null);
		Test.stopTest();
	}

	@isTest static void testValidarClienteCedulaCiudadaniaOrExtrajeriaOrPasaporte() {
		Test.startTest();
			Account objCuenta = Ter_DataGenerator_cls.crearCuenta(true);
			FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('1245377192154','88556699','T100000000012', null);
			FieloPLT__Program__c objProgram = Ter_DataGenerator_cls.generateProgramFielo();
			insert  objProgram;

			objMember.FieloPLT__Program__c = objProgram.Id;
			Contact objContact = Ter_DataGenerator_cls.generateContact();
			objContact.AccountId = objCuenta.Id;
			insert objContact;

			objMember.FieloPLT__Contact__c = objContact.Id;
			objMember.F_IdentificationType__c = 'Cédula de ciudadanía';
			insert objMember;

			Ter_Negocio_Complementario__c objTienda = Ter_DataGenerator_cls.crearTTCC(false);
			insert objTienda;

			Ter_POS__c objPos = new Ter_POS__c();
			objPos.Ter_Usuario__c = UserInfo.getUserId();
			objPos.Name = 'Nombre POS';
			objPos.Ter_Codigo_DIAN__c = 'AVX';
			objPos.Ter_Negocio_Complementario__c = objTienda.Id;
			insert objPos;

			Ter_TDC_Home_Ctr.TDC_Wrapper objResult = Ter_TDC_Home_Ctr.validarCliente('Cédula de ciudadanía','88556699');
		
			System.assertEquals(false, objResult.blnError);
			System.assertNotEquals(null, objResult.idMemberId);
			System.assertNotEquals(null, objResult.strNumeroDocumento);
			System.assertEquals('Cristian Jose Mosquera Puello', objResult.strNombre);
		Test.stopTest();
	}

	@isTest static void testGuardarVentaAcumulacion() {

		Configuracion_General__c objConfiguracion_General = Ter_DataGenerator_cls.generateCustomSettingsGeneral();
		insert objConfiguracion_General;

		Fielo_ParametrosLifeMiles__c objFielo_ParametrosLifeMiles = Ter_DataGenerator_cls.generateCustomSettingsLifeMiles();
		insert objFielo_ParametrosLifeMiles;

		list<Ter_Codigos_Errores__c> lstCodErrores = Ter_DataGenerator_cls.generarCodigosError(true);
		list<Ter_Homologacion_Listas__c> lstHomologacion_Listas = Ter_DataGenerator_cls.crearDatosHomologados(true);
		list<Fielo_RedirectURLs_ClubTerpel__c> lstRedirectURLs = Ter_DataGenerator_cls.crearRedirectURLs(true);
		FieloPLT__Program__c objFieloPLTProgram = Ter_DataGenerator_cls.crearFieloProgram(true);
		FieloPLT__Segment__c objFieloPLSegment = Ter_DataGenerator_cls.crearSegmento(true, objFieloPLTProgram.Id);
		FieloPLT__PointType__c objFieloPLTPointType = Ter_DataGenerator_cls.crearFieloPointType(true);
		FieloPLT__ProgramPointType__c objFieloPLTProgramPointType = Ter_DataGenerator_cls.crearProgramPointType(true, objFieloPLTProgram.Id, objFieloPLTPointType.Id);
		Fielo_VariablesFraude__c  objFieloVariablesFraude = Ter_DataGenerator_cls.crearVariablesFraude(true);

		Test.startTest();
			Account objCuenta = Ter_DataGenerator_cls.crearCuenta(true);
			FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('1245377192154','88556699','T100000000012', null);
			FieloPLT__Program__c objProgram = Ter_DataGenerator_cls.generateProgramFielo();
			insert  objProgram;

			objMember.FieloPLT__Program__c = objProgram.Id;
			Contact objContact = Ter_DataGenerator_cls.generateContact();
			objContact.AccountId = objCuenta.Id;
			insert objContact;

			objMember.FieloPLT__Contact__c = objContact.Id;
			insert objMember;

			Ter_Negocio_Complementario__c objTienda = Ter_DataGenerator_cls.crearTTCC(false);
			insert objTienda;

			Ter_POS__c objPos = new Ter_POS__c();
			objPos.Ter_Usuario__c = UserInfo.getUserId();
			objPos.Name = 'Nombre POS';
			objPos.Ter_Codigo_DIAN__c = 'AVX';
			objPos.Ter_Negocio_Complementario__c = objTienda.Id;
			insert objPos;

			Ter_TDC_Home_Ctr.TDC_Wrapper objResult = Ter_TDC_Home_Ctr.validarCliente('NLM','1245377192154');
			objResult.strNumeroFactura = '10987654321';
			objResult.strTipoTransaccion = Ter_TDC_Home_Ctr.TRANSACCION_ACUMULACION;
			objResult = Ter_TDC_Home_Ctr.guardarVenta(objResult);

			System.assertEquals(false, objResult.blnError);
		Test.stopTest();
	}



	@isTest static void testLogout() {
		Ter_TDC_Home_Ctr objTDCHomeCtr = new Ter_TDC_Home_Ctr();
		objTDCHomeCtr.logout();
	}

	@isTest static void testInitData() {
		Test.startTest();
			Ter_TDC_Valor_Milla__c objCustomConf = new Ter_TDC_Valor_Milla__c();
			objCustomConf.Name = 'ValorMilla';
			objCustomConf.Ter_TDC_Valor_Milla__c = 21;
			insert objCustomConf;

			Ter_Negocio_Complementario__c objTienda = Ter_DataGenerator_cls.crearTTCC(true);
			Ter_POS__c objPos = new Ter_POS__c();
			objPos.Ter_Usuario__c = UserInfo.getUserId();
			objPos.Name = 'Nombre POS';
			objPos.Ter_Codigo_DIAN__c = 'AVX';
			objPos.Ter_Negocio_Complementario__c = objTienda.Id;
			insert objPos;

			Ter_TDC_Home_Ctr.TDC_InitDataWrapper objResult = Ter_TDC_Home_Ctr.getInitData();
			System.assertEquals(objPos.Name, objResult.strNombreTienda);
		Test.stopTest();
	}
}