src/objects/Fielo_ItemVenta__c.object
<CustomObject>
    <fields>
        <fullName>F_Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_Venta__c</fullName>
        <label>Venta</label>
        <referenceTo>Fielo_Venta__c</referenceTo>
        <relationshipLabel>Itens de Venda</relationshipLabel>
        <relationshipName>Itens_de_Venda</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Item Venta</label>
    <nameField>
        <displayFormat>IV-{0000000000}</displayFormat>
        <label># Item Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fielo_MedioDePago__c.object
<CustomObject>
    <fields>
        <fullName>F_Acumula__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acumula</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Inactivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Medio de Pago</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medios de Pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_MedioDePagoVenta__c.object
<CustomObject>
    <fields>
        <fullName>F_MedioDePago__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Medio de Pago</label>
        <referenceTo>Fielo_MedioDePago__c</referenceTo>
        <relationshipLabel>Medios de Pago Venta</relationshipLabel>
        <relationshipName>Medios_de_Pago_Venta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_Monto__c</fullName>
        <label>Monto</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>F_Venta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venta</label>
        <referenceTo>Fielo_Venta__c</referenceTo>
        <relationshipLabel>Medios de Pago Venta</relationshipLabel>
        <relationshipName>Medios_de_Pago_Venta</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medio de Pago Venta</label>
    <nameField>
        <displayFormat>MPV-{0000000000}</displayFormat>
        <label># MP Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medios de Pago Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_TasaConversion__c.object
<CustomObject>
    <fields>
        <fullName>F_ConversionMonedas__c</fullName>
        <label>Conversión Monedas</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>COP -&gt; USD</fullName>
                    <default>true</default>
                    <label>COP -&gt; USD</label>
                </value>
                <value>
                    <fullName>USD -&gt; COP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_FactorConversion__c</fullName>
        <label>Factor de Conversión</label>
        <precision>16</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_FechaFin__c</fullName>
        <label>Fecha de Fin</label>
        <type>Date</type>
    </fields>
    <label>Tasa de Conversión</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasas de Conversión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_VariablesFraude__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de las variables utilizadas para el control de Fraudes de Acumulación Club Terpel</description>
    <fields>
        <fullName>F_MaxCantidadVentasLiquido__c</fullName>
        <description>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</description>
        <inlineHelpText>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</inlineHelpText>
        <label>Cantidad Máxima de Ventas (Líquidos)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxCantidadVentasTienda__c</fullName>
        <description>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</description>
        <inlineHelpText>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</inlineHelpText>
        <label>Cantidad Máxima de Ventas (Tienda)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxGalonesCorriente__c</fullName>
        <description>Número entero de galones máximos permitidos por venta</description>
        <inlineHelpText>Número entero de galones máximos permitidos por venta</inlineHelpText>
        <label>Galones Máximos Combustible Corriente</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxGalonesDiesel__c</fullName>
        <description>Número entero de galones máximos permitidos por venta</description>
        <inlineHelpText>Número entero de galones máximos permitidos por venta</inlineHelpText>
        <label>Galones Máximos Combustible Diesel</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxGalonesExtra__c</fullName>
        <description>Número entero de galones máximos permitidos por venta</description>
        <inlineHelpText>Número entero de galones máximos permitidos por venta</inlineHelpText>
        <label>Galones Máximos Combustible Extra</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxMontoVentaTienda__c</fullName>
        <description>Número entero de COP máximo permitido para una transacción de origen Tienda</description>
        <inlineHelpText>Número entero de COP máximo permitido para una transacción de origen Tienda</inlineHelpText>
        <label>Monto Máximo por Venta (Tienda)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>F_MinTiempoEntreVentas__c</fullName>
        <description>Número entero de segundos que deben pasar entre 2 transacciones de acumulación del mismo usuario</description>
        <inlineHelpText>Número entero de segundos que deben pasar entre 2 transacciones de acumulación del mismo usuario</inlineHelpText>
        <label>Tiempo Mínimos entre Ventas (seg)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_PeriodoInfracciones__c</fullName>
        <description>Número entero de días hacia atrás en los que tendrán en cuenta las infracciones cometidas.</description>
        <inlineHelpText>Número entero de días hacia atrás en los que tendrán en cuenta las infracciones cometidas.</inlineHelpText>
        <label>Período de infracciones</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Fielo - Variables de Fraude</label>
</CustomObject>

src/objects/Fielo_Venta__c.object
<CustomObject>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>Procesar</fullName>
                </value>
                <value>
                    <fullName>Aprobada</fullName>
                </value>
                <value>
                    <fullName>Rechazada</fullName>
                </value>
                <value>
                    <fullName>Reintentar</fullName>
                </value>
                <value>
                    <fullName>Revertida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_LiquidoFidelizable__c</fullName>
        <label>Líquido Fidelizable (Gal)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MontoFidelizableUSD__c</fullName>
        <label>Monto Fidelizable (USD)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MontoFidelizable__c</fullName>
        <label>Monto Fidelizable (COP)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MontoNoFidelizables__c</fullName>
        <label>Monto Medios No Fidelizables</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MontoTotal__c</fullName>
        <label>Monto Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>F_OrigenVenta__c</fullName>
        <label>Origen Venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Estación de Servicio</fullName>
                </value>
                <value>
                    <fullName>Tienda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_TipoCombustible__c</fullName>
        <label>Tipo de Combustible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corriente</fullName>
                </value>
                <value>
                    <fullName>Diesel</fullName>
                </value>
                <value>
                    <fullName>Extra</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Venta</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Numero Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Fielo_TRIG_VentaAfter.cls
/*******************************************************************************
*                          Copyright (C) 2017 ValueNET
* ------------------------------------------------------------------------------
* Author: EBC                          date: 24/05/2017
* 
* Name: Fielo_TRIG_VentaAfter.cls
* 
* Class for after event of Fielo Venta
*
*******************************************************************************/
public with sharing class Fielo_TRIG_VentaAfter {
    // Origin Venta
    public final static String TIENDA = 'Tienda';
    public final static String ESTACION_DE_SERVICIO = 'Estación de Servicio';

    // Type Combustible
    public final static String EXTRA = 'Extra';
    public final static String DIESEL = 'Diesel';
    public final static String CORRIENTE = 'Corriente';

    // Status Venta 
    public final static String PROCESAR = 'Procesar';
    public final static String APROBADA = 'Aprobada';
    public final static String RECHAZADA = 'Rechazada';
    public final static String REVERTIDA = 'Revertida';

    public static boolean ISRUNNING = false;
    

    // Custom Settings for Variables Fraude
    private static final Fielo_VariablesFraude__c VARIABLES_FRAUDE = 
                Fielo_VariablesFraude__c.getInstance('Fielo - Club Terpel');

    private static final Decimal MAX_GALONES_EXTRA = VARIABLES_FRAUDE.F_MaxGalonesExtra__c;
    private static final Decimal MAX_GALONES_DIESEL = VARIABLES_FRAUDE.F_MaxGalonesDiesel__c;
    private static final Decimal PERIODO_INFRACCIONES = VARIABLES_FRAUDE.F_PeriodoInfracciones__c;
    private static final Decimal MAX_GALONES_CORRIENTE = VARIABLES_FRAUDE.F_MaxGalonesCorriente__c;
    private static final Decimal MAX_MONTO_VENTA_TIENDA = VARIABLES_FRAUDE.F_MaxMontoVentaTienda__c;
    private static final Decimal MIN_TIEMPO_ENTRE_VENTAS = VARIABLES_FRAUDE.F_MinTiempoEntreVentas__c;
    private static final Decimal MAX_CANTIDAD_VENTAS_TIENDA = VARIABLES_FRAUDE.F_MaxCantidadVentasTienda__c;
    private static final Decimal MAX_CANTIDAD_VENTAS_LIQUIDO = VARIABLES_FRAUDE.F_MaxCantidadVentasLiquido__c;

    private static Decimal factorConversion {get{
                                    if(factorConversion == null){     
                                        List<Fielo_TasaConversion__c> lTasConLst = [
                                            SELECT F_FactorConversion__c   
                                            FROM Fielo_TasaConversion__c 
                                            WHERE F_ConversionMonedas__c = 'COP -> USD' 
                                            ORDER BY F_FechaFin__c DESC LIMIT 1];

                                        factorConversion = lTasConLst.size() > 0 ? lTasConLst.get(0).F_FactorConversion__c : null;                                                                                                                                                            
                                    }
                                    return factorConversion;
                                }}  

    public static void montosFidelizables() {

        TriggerCheck.assert();

        Map<Id,Fielo_Venta__c> lVentaTypeEstacionServMap = new Map<Id,Fielo_Venta__c>();
        Map<Id,Fielo_Venta__c> lVentaTypeTiendaMap = new Map<Id,Fielo_Venta__c>();

        // Search venta witch state is updated for the method fraud control
        for(Fielo_Venta__c vt :[SELECT F_Estado__c FROM Fielo_Venta__c WHERE id IN :trigger.newmap.keySet()]) {

            if( vt.F_Estado__c == PROCESAR  ) {
                Fielo_Venta__c lVentaAux = (Fielo_Venta__c) trigger.newmap.get(vt.id).clone(true, true, true, true);

                if( lVentaAux.F_OrigenVenta__c == ESTACION_DE_SERVICIO ) {
                    lVentaAux.F_Estado__c = APROBADA;
                    lVentaTypeEstacionServMap.put(lVentaAux.id, lVentaAux);
                }
                
                if( lVentaAux.F_OrigenVenta__c == TIENDA ) {
                    lVentaAux.F_Estado__c = APROBADA;
                    lVentaTypeTiendaMap.put(lVentaAux.id, lVentaAux);
                }   
            }
                         
        }

        if((lVentaTypeEstacionServMap.size() == 0) && (lVentaTypeTiendaMap.size() ==0)) return;
        
        for(AggregateResult ar: [SELECT F_Venta__c venta, sum(F_Cantidad__c) qtde
                                FROM Fielo_ItemVenta__c 
                                WHERE F_Venta__c IN :lVentaTypeEstacionServMap.keySet()
                                GROUP BY F_Venta__c]) {
            Fielo_Venta__c lVenta = lVentaTypeEstacionServMap.get(String.valueOf(ar.get('venta')));
            if(lVenta != null) {
                lVenta.F_LiquidoFidelizable__c = math.floor((Decimal)ar.get('qtde'));
                // Rule 1
                if( lVenta.F_TipoCombustible__c == CORRIENTE && 
                    lVenta.F_LiquidoFidelizable__c > MAX_GALONES_CORRIENTE ) {
                    
                    lVenta.F_LiquidoFidelizable__c = MAX_GALONES_CORRIENTE;
                }
                // Rule 2
                else if( lVenta.F_TipoCombustible__c == EXTRA && 
                    lVenta.F_LiquidoFidelizable__c  > MAX_GALONES_EXTRA) {

                    lVenta.F_LiquidoFidelizable__c  = MAX_GALONES_EXTRA;
                }
                // Rule 3
                else if( lVenta.F_TipoCombustible__c == DIESEL && 
                    lVenta.F_LiquidoFidelizable__c  > MAX_GALONES_DIESEL ) {
                    
                    lVenta.F_LiquidoFidelizable__c  = MAX_GALONES_DIESEL;
                }
            }           
        }  

        Map<Id, Decimal> lMontoNofidelizableMap = new Map<Id, Decimal>();
        for(AggregateResult ar: [SELECT F_Venta__c venta, sum(F_Monto__c) soma
                                FROM Fielo_MedioDePagoVenta__c 
                                WHERE F_Venta__c IN :lVentaTypeTiendaMap.keySet()
                                AND F_MedioDePago__r.F_Acumula__c = false
                                GROUP BY F_Venta__c]) {
            lMontoNofidelizableMap.put( (Id) ar.get('venta'), (Decimal) ar.get('soma'));        
        }

        for(Fielo_Venta__c vt :lVentaTypeTiendaMap.values()) {

            Decimal lMontoAux = lMontoNofidelizableMap.get(vt.id);
            if(lMontoAux == null) lMontoAux = 0;

            vt.F_MontoNoFidelizables__c = lMontoAux;
            vt.F_MontoFidelizable__c = vt.F_MontoTotal__c - vt.F_MontoNoFidelizables__c;

            // Rule 4
            if(vt.F_MontoFidelizable__c > MAX_MONTO_VENTA_TIENDA) {

                vt.F_MontoFidelizable__c = MAX_MONTO_VENTA_TIENDA;
            }                
            
            if(factorConversion != null) {
                vt.F_MontoFidelizableUSD__c = math.floor(vt.F_MontoFidelizable__c * factorConversion);
            }
            else {
                vt.F_MontoFidelizableUSD__c.addError('Error: Factor Conversion not found.');
            }
        }

        List<Fielo_Venta__c> lVentaToUpdateLst = new List<Fielo_Venta__c>();
        if(!lVentaTypeEstacionServMap.values().isEmpty())
            lVentaToUpdateLst.addAll(lVentaTypeEstacionServMap.values());

        if(!lVentaTypeTiendaMap.values().isEmpty())
            lVentaToUpdateLst.addAll(lVentaTypeTiendaMap.values());

        if(lVentaToUpdateLst.isEmpty()) return;

        update lVentaToUpdateLst;

        if ( Trigger.isInsert ) {
            // Send to process venta aprobada
            system.debug('Process Records Insert: ' + lVentaToUpdateLst);
            //FieloPLT.SObjectService.processRecords(lVentaToUpdateLst, null);  
        }
        else if ( Trigger.isUpdate ) {
            // Get old values from venta aprobada to Process Records
            Map<Id,Fielo_Venta__c> lVentaOldToProcessMap = new Map<Id,Fielo_Venta__c>();
            for(Fielo_Venta__c vt :lVentaToUpdateLst) {

                lVentaOldToProcessMap.put(vt.id, (Fielo_Venta__c)Trigger.oldmap.get(vt.id));
            }
            // Send to process venta aprobada
            //system.debug('Process Records new Update: ' + lVentaToUpdateLst);
            //FieloPLT.SObjectService.processRecords(lVentaToUpdateLst, null); 
            system.debug('Process Records old Update: ' + lVentaOldToProcessMap.values());
            //FieloPLT.SObjectService.processRecords(lVentaToUpdateLst, lVentaOldToProcessMap);  
        }
    }  

    public static void revertVenta() {

        TriggerCheck.assert();

        Set<Id> lIdVentaSet = new Set<Id>();
        for(Fielo_Venta__c vt :(List<Fielo_Venta__c>)trigger.new) {

            if(TriggerCheck.isChangedTo(vt, Fielo_Venta__c.F_Estado__c, REVERTIDA)) {                

                lIdVentaSet.add(vt.id);  
            }
        }

        if(lIdVentaSet.isEmpty()) return;

        List<Id> lTransactionIdsLst = new List<Id>();
        Map<Id,Id> lTransactionIdsMap = new Map<Id,Id>();
        for(FieloPLT__Transaction__c lTransaction : [SELECT Id, F_Venta__c 
                                                    FROM FieloPLT__Transaction__c 
                                                    WHERE F_Venta__c IN :lIdVentaSet]){

             lTransactionIdsMap.put(lTransaction.Id, lTransaction.F_Venta__c);
             lTransactionIdsLst.add(lTransaction.Id);
        }

        if(lTransactionIdsLst.isEmpty()) return;

        Map<Id,String> lResultsMap = FieloPLT.TransactionService.revertTransactions(lTransactionIdsLst);
        if(lResultsMap != null){
            for(Id lTransactionId : lResultsMap.keySet()){
                Fielo_Venta__c lVenta = (Fielo_Venta__c) trigger.newmap.get(lTransactionIdsMap.get(lTransactionId));
                if(lVenta != null) {
                    lVenta.addError('Error: ' + lResultsMap.get(lTransactionId));
                }
            }
        }
    }
}