src/objects/Fielo_ItemVenta__c.object
<CustomObject>
    <fields>
        <fullName>F_IdProducto__c</fullName>
        <label>Id Producto</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_Venta__c</fullName>
        <label>Venta</label>
        <referenceTo>Fielo_Venta__c</referenceTo>
        <relationshipLabel>Itens de Venda</relationshipLabel>
        <relationshipName>Itens_de_Venda</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Item Venta</label>
    <nameField>
        <displayFormat>IV-{0000000000}</displayFormat>
        <label># Item Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fielo_MedioDePago__c.object
<CustomObject>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activo</fullName>
                </value>
                <value>
                    <fullName>Inactivo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Medio de Pago</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medios de Pago</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_MedioDePagoVenta__c.object
<CustomObject>
    <fields>
        <fullName>F_MedioDePago__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Medio de Pago</label>
        <referenceTo>Fielo_MedioDePago__c</referenceTo>
        <relationshipLabel>Medios de Pago Venta</relationshipLabel>
        <relationshipName>Medios_de_Pago_Venta</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_Venta__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Venta</label>
        <referenceTo>Fielo_Venta__c</referenceTo>
        <relationshipLabel>Medios de Pago Venta</relationshipLabel>
        <relationshipName>Medios_de_Pago_Venta</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Medio de Pago Venta</label>
    <nameField>
        <displayFormat>MPV-{0000000000}</displayFormat>
        <label># MP Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medios de Pago Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_TasaConversion__c.object
<CustomObject>
    <label>Tasa de Conversión</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasas de Conversión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_VariablesFraude__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de las variables utilizadas para el control de Fraudes de Acumulación Club Terpel</description>
    <label>Fielo - Variables de Fraude</label>
</CustomObject>

src/objects/Fielo_Venta__c.object
<CustomObject>
    <fields>
        <fullName>F_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_EstacionDeServicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estación de Servicio</label>
        <referenceTo>Ter_Estacion_de_Servicio__c</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>Procesar</fullName>
                </value>
                <value>
                    <fullName>Aprobada</fullName>
                </value>
                <value>
                    <fullName>Rechazada</fullName>
                </value>
                <value>
                    <fullName>Reintentar</fullName>
                </value>
                <value>
                    <fullName>Revertida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_OrigenVenta__c</fullName>
        <label>Origen Venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Estación de Servicio</fullName>
                </value>
                <value>
                    <fullName>Tienda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Venta</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Numero Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ter_Estacion_de_Servicio__c.object
<CustomObject>
    <description>Este objeto contiene los registros de las estaciones de servicio de Terpel asociadas a sus operadores.</description>
    <label>Estación de Servicio</label>
    <nameField>
        <label>Nombre EDS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estaciones de Servicio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Fielo_VentaAfterTest.cls
/*******************************************************************************
*                          Copyright (C) 2017 ValueNET
* ------------------------------------------------------------------------------
* Author: EBC                          date: 30/05/2017
* 
* Name: Fielo_VentaAfterTest.trigger
* 
* Classe de teste da trigger Fielo_OnVentaAfter.trigger
*
*******************************************************************************/
@isTest
private class Fielo_VentaAfterTest {
	
	public final static String VENTA_TYPE_LIQUIDO_ID = RecType.getID('Fielo_Venta__c', 'Líquido');
	public final static String VENTA_TYPE_TIENDA_ID = RecType.getID('Fielo_Venta__c', 'Tienda');

	// Origin Venta
	public final static String TIENDA = 'Tienda';
	public final static String ESTACION_DE_SERVICIO = 'Estación de Servicio';

	// Type Combustible
	public final static String EXTRA = 'Extra';
	public final static String DIESEL = 'Diesel';
	public final static String CORRIENTE = 'Corriente';

	// Status Venta	
	public final static String PROCESAR = 'Procesar';
	public final static String APROBADA = 'Aprobada';
	public final static String RECHAZADA = 'Rechazada';

	@isTest static void montosFidelizables() {		

		Test.startTest();

			Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
			insert lVariablesFraude;

			FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
			insert lPrg; 

			FieloPLT__Member__c lMb = SObjectForTest.loadMember();

			Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
			insert lTasa;

			Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
			insert lEstacion;

			Fielo_Venta__c lVenta = SObjectForTest.getVenta();
			lVenta.F_EstacionDeServicio__c = lEstacion.id;
			lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
			lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
			lVenta.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
			insert lVenta;

			Fielo_MedioDePago__c lMedPago = SObjectForTest.getMedioDePago();
			insert lMedPago;

			Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();
			lMedPagoVenta.F_MedioDePago__c = lMedPago.id;
			lMedPagoVenta.F_Venta__c = lVenta.id;
			insert lMedPagoVenta;

			Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
			lItemVenta.F_Venta__c = lVenta.id;
			lItemVenta.F_IdProducto__c = '1';
			insert lItemVenta;

			lVenta.RecordTypeId = VENTA_TYPE_TIENDA_ID;
			lVenta.F_OrigenVenta__c = TIENDA;
			lVenta.F_Estado__c  = 'Procesar';
			update lVenta;

			lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
			lVenta.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
			lVenta.F_Estado__c  = 'Procesar';
			update lVenta;
			
		Test.stopTest();
	}
}