src/objects/Fielo_Autorizacion_LifeMiles__c.object
<CustomObject>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Revertido</fullName>
                </value>
                <value>
                    <fullName>Reintentar</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Autorizaciones LifeMiles</relationshipLabel>
        <relationshipName>Autorizaciones_LifeMiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_NumeroLifeMiles__c</fullName>
        <label>Número LifeMiles</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_ReintentosConexionLM__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reintentos Conexión LM</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Autorización LifeMiles</label>
    <nameField>
        <displayFormat>LM-{0000000000}</displayFormat>
        <label># Autorización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autorizacións LifeMiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_ParametrosLifeMiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parámetros de las integraciones de LifeMiles</description>
    <label>Fielo - Parámetros LifeMiles</label>
</CustomObject>

src/classes/Ter_RetryMilsesConversion_tst.cls
/**
* Avanxo Colombia
* @author 			Cristian Jose Mosquera Puello href=<cmosquera@avanxo.com>
* Project:			Terperl
* Description:		Classe encargada de ejecutar  las pruebas de la clase Ter_RetryMilsesConversion_cls
*					
* Changes (Version)
* -------------------------------------
*			No.		Date			Author					Description
*			-----	----------		--------------------	---------------
* @version	1.0		31/05/2017		Cristian Mosquera (CM)		Implementacion inicial de la clase de prueba.
**/
@isTest
public class Ter_RetryMilsesConversion_tst {

    /**
     * Metodo encargado de realizar las pruebas unitarias del metodo execute.
     */
    @isTest
    private static void textExecute() {
        Fielo_ParametrosLifeMiles__c cs = Ter_DataGenerator_cls.generateCustomSettingsLifeMiles();
        insert cs;
        Configuracion_General__c csp = Ter_DataGenerator_cls.generateCustomSettingsGeneral();
        insert csp;

        Account account = Ter_DataGenerator_cls.crearCuenta(true);
        Ter_RetryMilsesConversion_cls retriMilesConversion =
                new Ter_RetryMilsesConversion_cls();

        
        Fielo_Autorizacion_LifeMiles__c objAuth =
                Ter_DataGenerator_cls.generateDataAuthFieloLifeMiles();
        FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('5455','545544','5454', null);
        FieloPLT__Program__c program = Ter_DataGenerator_cls.generateProgramFielo();

        insert  program;

        objMember.FieloPLT__Program__c = program.Id;

        Contact contact = Ter_DataGenerator_cls.generateContact ();

        contact.AccountId = account.Id;

        insert contact;

        objMember.FieloPLT__Contact__c = contact.Id;
        insert objMember;


        objAuth.F_Estado__c = Label.TER_STATUS_RETRY_CONVERSION_WS;
        objAuth.F_Member__c = objMember.id;
        objAuth.F_NumeroLifeMiles__c = objMember.F_NumeroLifeMiles__c;
        insert objAuth;
        Test.startTest();
	        Test.setMock(WebServiceMock.class, new Ter_ConversionWsMock_cls('000'));
	        retriMilesConversion.execute(null);
	        
        Test.stopTest();
        Fielo_Autorizacion_LifeMiles__c objAuthorizationFind =
            [SELECT ID, F_Estado__c, F_ReintentosConexionLM__c
                    FROM Fielo_Autorizacion_LifeMiles__c WHERE Id  = :objAuth.Id];
        //System.assertEquals(Label.TER_STATUS_SUCESS_CONVERSION_WS, objAuthorizationFind.F_Estado__c);
    }
    
    @isTest
    private static void textExecute2() {
        Fielo_ParametrosLifeMiles__c cs = Ter_DataGenerator_cls.generateCustomSettingsLifeMiles();
        insert cs;
        Configuracion_General__c csp = Ter_DataGenerator_cls.generateCustomSettingsGeneral();
        insert csp;

        Account account = Ter_DataGenerator_cls.crearCuenta(true);
        Ter_RetryMilsesConversion_cls retriMilesConversion =
                new Ter_RetryMilsesConversion_cls();

        
        Fielo_Autorizacion_LifeMiles__c objAuth =
                Ter_DataGenerator_cls.generateDataAuthFieloLifeMiles();
        FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('5455','545544','5454', null);
        FieloPLT__Program__c program = Ter_DataGenerator_cls.generateProgramFielo();

        insert  program;

        objMember.FieloPLT__Program__c = program.Id;

        Contact contact = Ter_DataGenerator_cls.generateContact ();

        contact.AccountId = account.Id;

        insert contact;

        objMember.FieloPLT__Contact__c = contact.Id;
        insert objMember;


        objAuth.F_Estado__c = Label.TER_STATUS_RETRY_CONVERSION_WS;
        objAuth.F_Member__c = objMember.id;
        objAuth.F_NumeroLifeMiles__c = objMember.F_NumeroLifeMiles__c;
        insert objAuth;
        Test.startTest();
	        
	        Test.setMock(WebServiceMock.class, new Ter_ConversionWsMock_cls('010'));
	        retriMilesConversion.execute(null);
	        
        Test.stopTest();
        Fielo_Autorizacion_LifeMiles__c objAuthorizationFind =
            [SELECT ID, F_Estado__c, F_ReintentosConexionLM__c
                    FROM Fielo_Autorizacion_LifeMiles__c WHERE Id  = :objAuth.Id];
        //System.assertEquals(Label.TER_STATUS_SUCESS_CONVERSION_WS, objAuthorizationFind.F_Estado__c);
    }
    
    @isTest
    private static void textExecute3() {
        Fielo_ParametrosLifeMiles__c cs = Ter_DataGenerator_cls.generateCustomSettingsLifeMiles();
        insert cs;
        Configuracion_General__c csp = Ter_DataGenerator_cls.generateCustomSettingsGeneral();
        insert csp;

        Account account = Ter_DataGenerator_cls.crearCuenta(true);
        Ter_RetryMilsesConversion_cls retriMilesConversion =
                new Ter_RetryMilsesConversion_cls();

        
        Fielo_Autorizacion_LifeMiles__c objAuth =
                Ter_DataGenerator_cls.generateDataAuthFieloLifeMiles();
        FieloPLT__Member__c objMember = Ter_DataGenerator_cls.generateMember('5455','545544','5454', null);
        FieloPLT__Program__c program = Ter_DataGenerator_cls.generateProgramFielo();

        insert  program;

        objMember.FieloPLT__Program__c = program.Id;

        Contact contact = Ter_DataGenerator_cls.generateContact ();

        contact.AccountId = account.Id;

        insert contact;

        objMember.FieloPLT__Contact__c = contact.Id;
        insert objMember;


        objAuth.F_Estado__c = Label.TER_STATUS_RETRY_CONVERSION_WS;
        objAuth.F_Member__c = objMember.id;
        objAuth.F_NumeroLifeMiles__c = objMember.F_NumeroLifeMiles__c;
        insert objAuth;
        Test.startTest();
	        Test.setMock(WebServiceMock.class, new Ter_ConversionWsMock_cls('XXX'));
	        retriMilesConversion.execute(null);
        Test.stopTest();
        Fielo_Autorizacion_LifeMiles__c objAuthorizationFind =
            [SELECT ID, F_Estado__c, F_ReintentosConexionLM__c
                    FROM Fielo_Autorizacion_LifeMiles__c WHERE Id  = :objAuth.Id];
        //System.assertEquals(Label.TER_STATUS_SUCESS_CONVERSION_WS, objAuthorizationFind.F_Estado__c);
    }


}