src/objects/Fielo_ItemVenta__c.object
<CustomObject>
    <fields>
        <fullName>F_Cantidad__c</fullName>
        <label>Cantidad</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_IdProducto__c</fullName>
        <label>Id Producto</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Item Venta</label>
    <nameField>
        <displayFormat>IV-{0000000000}</displayFormat>
        <label># Item Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Items de Venta</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Fielo_MedioDePagoVenta__c.object
<CustomObject>
    <label>Medio de Pago Venta</label>
    <nameField>
        <displayFormat>MPV-{0000000000}</displayFormat>
        <label># MP Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medios de Pago Venta</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_TasaConversion__c.object
<CustomObject>
    <label>Tasa de Conversión</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasas de Conversión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_VariablesFraude__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de las variables utilizadas para el control de Fraudes de Acumulación Club Terpel</description>
    <fields>
        <fullName>F_MaxCantidadVentasLiquido__c</fullName>
        <description>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</description>
        <inlineHelpText>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</inlineHelpText>
        <label>Cantidad Máxima de Ventas (Líquidos)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxCantidadVentasTienda__c</fullName>
        <description>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</description>
        <inlineHelpText>Número entero de transacciones de acumulación máximas permitidas por usuario durante el mísmo día.</inlineHelpText>
        <label>Cantidad Máxima de Ventas (Tienda)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxGalonesCorriente__c</fullName>
        <description>Número entero de galones máximos permitidos por venta</description>
        <inlineHelpText>Número entero de galones máximos permitidos por venta</inlineHelpText>
        <label>Galones Máximos Combustible Corriente</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_MaxMontoVentaTienda__c</fullName>
        <description>Número entero de COP máximo permitido para una transacción de origen Tienda</description>
        <inlineHelpText>Número entero de COP máximo permitido para una transacción de origen Tienda</inlineHelpText>
        <label>Monto Máximo por Venta (Tienda)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <label>Fielo - Variables de Fraude</label>
</CustomObject>

src/objects/Fielo_Venta__c.object
<CustomObject>
    <fields>
        <fullName>F_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_EstacionDeServicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estación de Servicio</label>
        <referenceTo>Ter_Estacion_de_Servicio__c</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>Procesar</fullName>
                </value>
                <value>
                    <fullName>Aprobada</fullName>
                </value>
                <value>
                    <fullName>Rechazada</fullName>
                </value>
                <value>
                    <fullName>Reintentar</fullName>
                </value>
                <value>
                    <fullName>Revertida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_FechaTransaccion__c</fullName>
        <label>Fecha de Transacción</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>F_LiquidoFidelizable__c</fullName>
        <label>Líquido Fidelizable (Gal)</label>
        <precision>16</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_MontoTotal__c</fullName>
        <label>Monto Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>F_OrigenVenta__c</fullName>
        <label>Origen Venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Estación de Servicio</fullName>
                </value>
                <value>
                    <fullName>Tienda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_TipoCombustible__c</fullName>
        <label>Tipo de Combustible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Corriente</fullName>
                </value>
                <value>
                    <fullName>Diesel</fullName>
                </value>
                <value>
                    <fullName>Extra</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Venta</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Numero Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ter_Estacion_de_Servicio__c.object
<CustomObject>
    <description>Este objeto contiene los registros de las estaciones de servicio de Terpel asociadas a sus operadores.</description>
    <label>Estación de Servicio</label>
    <nameField>
        <label>Nombre EDS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estaciones de Servicio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Fielo_SimuladorTest.cls
/*******************************************************************************
*                          Copyright (C) 2017 ValueNET
* ------------------------------------------------------------------------------
* Author: EBC                          date: 26/06/2017
* 
* Name: Fielo_SimuladorTest.cls
* 
* Classe de teste da trigger Fielo_Simulador.trigger
*
*******************************************************************************/
@isTest
private class Fielo_SimuladorTest {

	public final static String VENTA_TYPE_LIQUIDO_ID = RecType.getID('Fielo_Venta__c', 'Líquido');
	public final static String VENTA_TYPE_TIENDA_ID = RecType.getID('Fielo_Venta__c', 'Tienda');

	// Origin Venta
	public final static String TIENDA = 'Tienda';
	public final static String ESTACION_DE_SERVICIO = 'Estación de Servicio';

	// Type Combustible
	public final static String EXTRA = 'Extra';
	public final static String DIESEL = 'Diesel';
	public final static String CORRIENTE = 'Corriente';

	// Status Venta	
	public final static String PROCESAR = 'Procesar';
	public final static String APROBADA = 'Aprobada';
	public final static String RECHAZADA = 'Rechazada';

	@isTest static void simulateVentaLiquid() {
		
		Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
		insert lVariablesFraude;

		FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
		insert lPrg; 

		FieloPLT__Member__c lMb = SObjectForTest.loadMember();

		Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
		insert lTasa;

		Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
		insert lEstacion;

		Fielo_Venta__c lVenta = SObjectForTest.getVenta();
		lVenta.F_EstacionDeServicio__c = lEstacion.id;
		lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
		lVenta.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
		lVenta.F_FechaTransaccion__c = Datetime.now();
		lVenta.F_Estado__c  = 'Pendiente';

		Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();

		Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
		lItemVenta.F_IdProducto__c = '1';
		lItemVenta.F_Cantidad__c = 51;

		Test.startTest();

			Map<String, List<SObject>> lResultMap = Fielo_Simulador.SimularVenta(lVenta, new List<Fielo_ItemVenta__c>{lItemVenta}, new List<Fielo_MedioDePagoVenta__c>{lMedPagoVenta});

		Test.stopTest();
	}

	@isTest static void simulateVentaLiquidMaxCantidade() {
		
		Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
		lVariablesFraude.F_MaxCantidadVentasLiquido__c = 1;
		insert lVariablesFraude;

		FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
		insert lPrg; 

		FieloPLT__Member__c lMb = SObjectForTest.loadMember();

		Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
		insert lTasa;

		Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
		insert lEstacion;

		Fielo_Venta__c lVentaBase = SObjectForTest.getVenta();
		lVentaBase.F_EstacionDeServicio__c = lEstacion.id;
		lVentaBase.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVentaBase.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
		lVentaBase.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
		lVentaBase.F_FechaTransaccion__c = Datetime.now();
		lVentaBase.F_Estado__c  = 'Pendiente';
		insert lVentaBase;

		Fielo_Venta__c lVenta = SObjectForTest.getVenta();
		lVenta.F_LiquidoFidelizable__c = lVariablesFraude.F_MaxGalonesCorriente__c + 1;
		lVenta.F_EstacionDeServicio__c = lEstacion.id;
		lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
		lVenta.F_TipoCombustible__c = EXTRA;
		lVenta.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
		lVenta.F_FechaTransaccion__c = Datetime.now();
		lVenta.F_Estado__c  = 'Pendiente';

		Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();

		Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
		lItemVenta.F_IdProducto__c = '1';
		lItemVenta.F_Cantidad__c = 51;


		Test.startTest();

			Map<String, List<SObject>> lResultMap = Fielo_Simulador.SimularVenta(lVenta, new List<Fielo_ItemVenta__c>{lItemVenta}, new List<Fielo_MedioDePagoVenta__c>{lMedPagoVenta});

		Test.stopTest();
	}

	@isTest static void simulateVentaTienda() {
		
		Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
		insert lVariablesFraude;

		FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
		insert lPrg; 

		FieloPLT__Member__c lMb = SObjectForTest.loadMember();

		Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
		insert lTasa;

		Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
		insert lEstacion;

		Fielo_Venta__c lVenta = SObjectForTest.getVenta();
		lVenta.F_EstacionDeServicio__c = lEstacion.id;
		lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta.RecordTypeId = VENTA_TYPE_TIENDA_ID;
		lVenta.F_OrigenVenta__c = TIENDA;
		lVenta.F_FechaTransaccion__c = Datetime.now();
		lVenta.F_Estado__c  = 'Pendiente';

		Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();

		Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
		lItemVenta.F_IdProducto__c = '1';
		lItemVenta.F_Cantidad__c = 51;

		Test.startTest();

			Map<String, List<SObject>> lResultMap = Fielo_Simulador.SimularVenta(lVenta, new List<Fielo_ItemVenta__c>{lItemVenta}, new List<Fielo_MedioDePagoVenta__c>{lMedPagoVenta});

		Test.stopTest();
	}

	@isTest static void simulateVentaTiendaMaxCantidade() {
		
		Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
		lVariablesFraude.F_MaxCantidadVentasTienda__c = 1;
		insert lVariablesFraude;

		FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
		insert lPrg; 

		FieloPLT__Member__c lMb = SObjectForTest.loadMember();

		Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
		insert lTasa;

		Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
		insert lEstacion;

		Fielo_Venta__c lVentaBase = SObjectForTest.getVenta();
		lVentaBase.F_EstacionDeServicio__c = lEstacion.id;
		lVentaBase.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVentaBase.RecordTypeId = VENTA_TYPE_TIENDA_ID;
		lVentaBase.F_OrigenVenta__c = TIENDA;
		lVentaBase.F_FechaTransaccion__c = Datetime.now();
		lVentaBase.F_Estado__c  = 'Pendiente';
		insert lVentaBase;

		Fielo_Venta__c lVenta = SObjectForTest.getVenta();
		lVenta.F_MontoTotal__c = lVariablesFraude.F_MaxMontoVentaTienda__c + 1;
		lVenta.F_EstacionDeServicio__c = lEstacion.id;
		lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
		lVenta.F_OrigenVenta__c = TIENDA;
		lVenta.F_FechaTransaccion__c = Datetime.now();
		lVenta.F_Estado__c  = 'Pendiente';

		Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();

		Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
		lItemVenta.F_IdProducto__c = '1';
		lItemVenta.F_Cantidad__c = 51;

		Test.startTest();

			Map<String, List<SObject>> lResultMap = Fielo_Simulador.SimularVenta(lVenta, new List<Fielo_ItemVenta__c>{lItemVenta}, new List<Fielo_MedioDePagoVenta__c>{lMedPagoVenta});

		Test.stopTest();
	}

		@isTest static void simulateExtraComb() {
		
		Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
		lVariablesFraude.F_MaxCantidadVentasTienda__c = 2;
		insert lVariablesFraude;

		FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
		insert lPrg; 

		FieloPLT__Member__c lMb = SObjectForTest.loadMember();

		Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
		insert lTasa;

		Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
		insert lEstacion;

		Fielo_Venta__c lVentaBase = SObjectForTest.getVenta();
		lVentaBase.F_EstacionDeServicio__c = lEstacion.id;
		lVentaBase.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVentaBase.RecordTypeId = VENTA_TYPE_TIENDA_ID;
		lVentaBase.F_OrigenVenta__c = TIENDA;
		lVentaBase.F_FechaTransaccion__c = Datetime.now();
		lVentaBase.F_Estado__c  = 'Pendiente';
		insert lVentaBase;

		Fielo_Venta__c lVenta = SObjectForTest.getVenta();
		lVenta.F_MontoTotal__c = lVariablesFraude.F_MaxMontoVentaTienda__c + 1;
		lVenta.F_EstacionDeServicio__c = lEstacion.id;
		lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
		lVenta.F_OrigenVenta__c = TIENDA;
		lVenta.F_FechaTransaccion__c = Datetime.now();
		lVenta.F_Estado__c  = 'Pendiente';
		lVenta.F_Member__c = lMb.id;

		Fielo_Venta__c lVenta2 = SObjectForTest.getVenta();
		lVenta2.F_MontoTotal__c = lVariablesFraude.F_MaxMontoVentaTienda__c + 1;
		lVenta2.F_EstacionDeServicio__c = lEstacion.id;
		lVenta2.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta2.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
		lVenta2.F_OrigenVenta__c = TIENDA;
		lVenta2.F_FechaTransaccion__c = Datetime.now();
		lVenta2.F_Estado__c  = 'Pendiente';
		lVenta2.F_Member__c = lMb.id;
		insert lVenta2;

		Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();

		Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
		lItemVenta.F_IdProducto__c = '1';
		lItemVenta.F_Cantidad__c = 51;

		Test.startTest();

		Fielo_Simulador lSimulador = new Fielo_Simulador();

			Map<String, List<SObject>> lResultMap = Fielo_Simulador.SimularVenta(lVenta, new List<Fielo_ItemVenta__c>{}, new List<Fielo_MedioDePagoVenta__c>{lMedPagoVenta});

		Test.stopTest();
	}

	@isTest static void simulateVenta() {
		
		Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
		insert lVariablesFraude;

		FieloPLT__Program__c lPrg = SObjectForTest.getProgram('Teste'); 
		insert lPrg; 

		FieloPLT__Member__c lMb = SObjectForTest.loadMember();

		Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
		insert lTasa;

		Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
		insert lEstacion;

		Fielo_Venta__c lVentaBase = SObjectForTest.getVenta();
		lVentaBase.F_EstacionDeServicio__c = lEstacion.id;
		lVentaBase.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVentaBase.RecordTypeId = VENTA_TYPE_TIENDA_ID;
		lVentaBase.F_OrigenVenta__c = TIENDA;
		lVentaBase.F_FechaTransaccion__c = Datetime.now();
		lVentaBase.F_Estado__c  = 'Aprobada';
		insert lVentaBase;

		Fielo_Venta__c lVenta = SObjectForTest.getVenta();
		lVenta.F_EstacionDeServicio__c = lEstacion.id;
		lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
		lVenta.RecordTypeId = VENTA_TYPE_TIENDA_ID;
		lVenta.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
		lVenta.F_FechaTransaccion__c = Datetime.now();
		lVenta.F_Estado__c  = 'Pendiente';

		Fielo_MedioDePagoVenta__c lMedPagoVenta = SObjectForTest.getMedioDePagoVenta();

		Fielo_ItemVenta__c lItemVenta = SObjectForTest.getItemVenta();
		lItemVenta.F_IdProducto__c = '1';
		lItemVenta.F_Cantidad__c = 51;

		Test.startTest();

			Map<String, List<SObject>> lResultMap = Fielo_Simulador.SimularVenta(lVenta, new List<Fielo_ItemVenta__c>{lItemVenta}, new List<Fielo_MedioDePagoVenta__c>{lMedPagoVenta});

		Test.stopTest();
	}
}