src/objects/Fielo_Contactenos__c.object
<CustomObject>
    <fields>
        <fullName>F_Asunto__c</fullName>
        <label>Asunto</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_Descripcion__c</fullName>
        <label>Descripción</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>F_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>F_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Contáctenos</relationshipLabel>
        <relationshipName>Contactenos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_Nombre__c</fullName>
        <label>Nombre</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_NumeroTelefono__c</fullName>
        <label>Número de Teléfono</label>
        <type>Phone</type>
    </fields>
    <label>Contactenos Fielo</label>
    <nameField>
        <displayFormat>CF-{000000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contáctenos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Widget3API.cls
global with sharing class Widget3API implements FieloCMS.ViewInterface{

    public FieloPLT__Member__c fMember { get; set; }
    public static String fNombre { get; set; }
    public static String fEmail { get; set; }
    public static String fTelefono { get; set; }
    public static String fAsunto { get; set; }
    public static String fDescripcion { get; set; }
    public static String fMsgError { get; set; }
    public static String fMsgInfo { get; set; }

    global ApexPages.Component getComponent(FieloCMS__Component__c c){                
        Component.Widget3 contactanos = new Component.Widget3(config=c);
        return contactanos;        
    }

  public Widget3API() {

        fMember = Fielo_UTIL_Member.getAllFieldsLoggedMember();         
    }

    public PageReference enviar() {
        Id lIdMember;
        fMsgError = fMsgInfo = null;

        if (fMember != null){
            fEmail = fMember.FieloPLT__Email__c;    
            fTelefono = fMember.F_Phone__c;
            fNombre = fMember.Name;     
            lIdMember = fMember.id;
        }

        if ( (fMember == null && (String.isBlank(fTelefono) || String.isBlank(fNombre) || String.isBlank(fEmail))) 
                || String.isBlank(fAsunto) || String.isBlank(fDescripcion) ){
            fMsgError = Label.Fielo_CamposRequeridos;
            return null;
        }

        if (!validaEMail(fEmail)) {
            fMsgError = Label.Fielo_InvalidEmail;
            return null;
        }

        Fielo_Contactenos__c lContactenos = new Fielo_Contactenos__c();
        lContactenos.F_Email__c = fEmail;
        lContactenos.F_Asunto__c = fAsunto;
        lContactenos.F_Nombre__c = fNombre;
        lContactenos.F_Member__c = lIdMember;
        lContactenos.F_Descripcion__c = fDescripcion;
        lContactenos.F_NumeroTelefono__c = fTelefono;

        try{
          insert lContactenos;
          fMsgInfo = Label.Fielo_ContactenosEnviado;
          clearFields();
      }
      catch(DmlException e) {

          fMsgError = 'Error: ' + e.getDmlMessage(0); 
      }

        return null;
    }

    private boolean validaEMail( string aEmail ) {
        if ( String.isBlank(aEmail) ) return false;
        Pattern MyPattern = Pattern.compile( '^[a-zA-Z0-9._|\\\\%#~`=?&/$^*!}{+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$' );
        Matcher MyMatcher = MyPattern.matcher( aEmail );
        return MyMatcher.matches();
  }

    private void clearFields() {
        fNombre = '';
        fEmail = '';
        fTelefono = '';
        fAsunto = '';
        fDescripcion = '';
    }
}