src/objects/Fielo_Autorizacion_LifeMiles__c.object
<CustomObject>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                </value>
                <value>
                    <fullName>Aprobado</fullName>
                </value>
                <value>
                    <fullName>Rechazado</fullName>
                </value>
                <value>
                    <fullName>Revertido</fullName>
                </value>
                <value>
                    <fullName>Reintentar</fullName>
                </value>
                <value>
                    <fullName>Cancelado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Autorizaciones LifeMiles</relationshipLabel>
        <relationshipName>Autorizaciones_LifeMiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_NumeroLifeMiles__c</fullName>
        <label>Número LifeMiles</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_TipoTransaccion__c</fullName>
        <label>Tipo de Transacción</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Crédito (C)</fullName>
                </value>
                <value>
                    <fullName>Débito (D)</fullName>
                </value>
                <value>
                    <fullName>Reversión (R)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_Venta__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Venta</label>
        <referenceTo>Fielo_Venta__c</referenceTo>
        <relationshipLabel>Autorizaciónes LifeMiles</relationshipLabel>
        <relationshipName>Autorizaciones_LifeMiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Autorización LifeMiles</label>
    <nameField>
        <displayFormat>LM-{0000000000}</displayFormat>
        <label># Autorización</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autorizacións LifeMiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_ParametrosLifeMiles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parámetros de las integraciones de LifeMiles</description>
    <label>Fielo - Parámetros LifeMiles</label>
</CustomObject>

src/objects/Fielo_TasaConversion__c.object
<CustomObject>
    <label>Tasa de Conversión</label>
    <nameField>
        <label>Nombre</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasas de Conversión</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Fielo_VariablesFraude__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Valores de las variables utilizadas para el control de Fraudes de Acumulación Club Terpel</description>
    <label>Fielo - Variables de Fraude</label>
</CustomObject>

src/objects/Fielo_Venta__c.object
<CustomObject>
    <fields>
        <fullName>F_Cliente__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cliente</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_EstacionDeServicio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estación de Servicio</label>
        <referenceTo>Ter_Estacion_de_Servicio__c</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_Estado__c</fullName>
        <label>Estado</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pendiente</fullName>
                    <default>true</default>
                    <label>Pendiente</label>
                </value>
                <value>
                    <fullName>Procesar</fullName>
                </value>
                <value>
                    <fullName>Aprobada</fullName>
                </value>
                <value>
                    <fullName>Rechazada</fullName>
                </value>
                <value>
                    <fullName>Reintentar</fullName>
                </value>
                <value>
                    <fullName>Revertida</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Ventas</relationshipLabel>
        <relationshipName>Ventas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>F_OrigenVenta__c</fullName>
        <label>Origen Venta</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Estación de Servicio</fullName>
                </value>
                <value>
                    <fullName>Tienda</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>F_TipoTransaccion__c</fullName>
        <label>Tipo de Transacción</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Acumulación</fullName>
                </value>
                <value>
                    <fullName>Redención</fullName>
                </value>
                <value>
                    <fullName>Reversión</fullName>
                </value>
                <value>
                    <fullName>Reclamación</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Venta</label>
    <nameField>
        <displayFormat>V-{0000000000}</displayFormat>
        <label>Numero Venta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ventas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Ter_Estacion_de_Servicio__c.object
<CustomObject>
    <description>Este objeto contiene los registros de las estaciones de servicio de Terpel asociadas a sus operadores.</description>
    <fields>
        <fullName>F_Acumula__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Acumula</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>F_ClubTerpel__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Habilitar para el programa de Fidelización &quot;Club Terpel&quot; (Fielo)</inlineHelpText>
        <label>Club Terpel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>F_IdFidelizacion__c</fullName>
        <externalId>true</externalId>
        <label>Id Fidelizacion</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>F_Reclama__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reclama</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>F_Redime__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Redime</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ter_Propia__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Este campo indica si la estación de servicio es propia.</description>
        <label>Propia</label>
        <type>Checkbox</type>
    </fields>
    <label>Estación de Servicio</label>
    <nameField>
        <label>Nombre EDS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estaciones de Servicio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Fielo_TRIG_AutorizacionLifeMilesAfterTst.cls
/*******************************************************************************
*                          Copyright (C) 2017 ValueNET
* ------------------------------------------------------------------------------
* Author: JNS                   date: 07/08/2017
* 
* Name: Fielo_TRIG_AutorizacionLifeMilesAfterTst.cls
* 
* Class for test Fielo_TRIG_AutorizacionLifeMilesAfter
*
*******************************************************************************/
@isTest
private class Fielo_TRIG_AutorizacionLifeMilesAfterTst
{
    public final static String VENTA_TYPE_LIQUIDO_ID = RecType.getID('Fielo_Venta__c', 'Líquido');
    public final static String VENTA_TYPE_TIENDA_ID = RecType.getID('Fielo_Venta__c', 'Tienda');

    // Origin Venta
    public final static String TIENDA = 'Tienda';
    public final static String ESTACION_DE_SERVICIO = 'Estación de Servicio';

    @isTest
    static void lifeMilesCredito() {

      Fielo_ParametrosLifeMiles__c cs = Ter_DataGenerator_cls.generateCustomSettingsLifeMiles();
        insert cs;
        Configuracion_General__c csp = Ter_DataGenerator_cls.generateCustomSettingsGeneral();
        insert csp;
        Ter_ConversionWsConsumer_cls
                conversionWsConsumer_cls = new Ter_ConversionWsConsumer_cls();
        Test.setMock(WebServiceMock.class, new Ter_ConversionWsMock_cls());        

      FieloPLT__Member__c LMemberCliente =  createMemberByAccount();

      Test.startTest();   

      system.runAs(LMemberCliente.FieloPLT__User__r) {
          Fielo_Autorizacion_LifeMiles__c lAutoLifeMiles = new Fielo_Autorizacion_LifeMiles__c();
          lAutoLifeMiles.F_NumeroLifeMiles__c = '123456789ASD';
          lAutoLifeMiles.F_Estado__c = 'Pendiente';
          lAutoLifeMiles.F_TipoTransaccion__c = 'Crédito (C)';
          insert lAutoLifeMiles;
      }

      Test.stopTest();
    }

    @isTest
    static void lifeMilesDebito() {

        Fielo_VariablesFraude__c lVariablesFraude = SObjectForTest.getVariablesFraude();
        insert lVariablesFraude;

        Fielo_ParametrosLifeMiles__c cs = Ter_DataGenerator_cls.generateCustomSettingsLifeMiles();
        insert cs;
        Configuracion_General__c csp = Ter_DataGenerator_cls.generateCustomSettingsGeneral();
        insert csp;
        Ter_ConversionWsConsumer_cls conversionWsConsumer_cls = new Ter_ConversionWsConsumer_cls();
        Test.setMock(WebServiceMock.class, new Ter_ConversionWsMock_cls());        

        FieloPLT__Member__c lMb =  createMemberByAccount();
        
        Fielo_TasaConversion__c lTasa = SObjectForTest.getTasaConversion();
        insert lTasa;

        Ter_Estacion_de_Servicio__c lEstacion = SObjectForTest.getEstacionDeServicio();
        lEstacion.Ter_Propia__c = true;
        lEstacion.F_Reclama__c = true;
        lEstacion.F_Redime__c = true;
        lEstacion.F_Acumula__c = true;
        lEstacion.F_ClubTerpel__c = true;
        lEstacion.F_IdFidelizacion__c = 'fielo123';
        insert lEstacion;

        FieloCMS__Category__c lCategoria = new FieloCMS__Category__c();
        lCategoria.Name = 'Catálogo - No Habilitados';
        insert lCategoria;      

        FieloPLT__Reward__c lReward = new FieloPLT__Reward__c();
        lReward.FieloPLT__Program__c = lMb.FieloPLT__Program__c;
        system.debug('## prog id: ' + lMb.FieloPLT__Program__c);
        lReward.Name = 'Redención Presencial Líquidos';
        lReward.FieloPLT__StockManagement__c = 'Unlimited';
        lReward.Category__c = lCategoria.id;
        lReward.FieloPLT__Points__c = 0;
        insert lReward;

        Fielo_Venta__c lVenta = SObjectForTest.getVenta();
        lVenta.F_EstacionDeServicio__c = lEstacion.id;
        lVenta.F_Cliente__c = lMb.FieloPLT__Account__c;
        lVenta.RecordTypeId = VENTA_TYPE_LIQUIDO_ID;
        lVenta.F_OrigenVenta__c = ESTACION_DE_SERVICIO;
        lVenta.F_Member__c = lMb.Id;
        insert lVenta;

        Test.startTest();   

        system.runAs(lMb.FieloPLT__User__r) {
            Fielo_Autorizacion_LifeMiles__c lAutoLifeMiles = new Fielo_Autorizacion_LifeMiles__c();
            lAutoLifeMiles.F_NumeroLifeMiles__c = '123456789ASD';
            lAutoLifeMiles.F_Estado__c = 'Aprobado';
            lAutoLifeMiles.F_TipoTransaccion__c = 'Débito (D)';
            lAutoLifeMiles.F_Venta__c = lVenta.id;
            lAutoLifeMiles.F_Member__c = lMb.Id;

            FieloPLT.SObjectService.enableAdminPermission(true);
            insert lAutoLifeMiles;
            FieloPLT.SObjectService.enableAdminPermission(false); 
        }

        Test.stopTest();
    }

    private static FieloPLT__Member__c createMemberByAccount() {

        FieloPLT__Program__c lPr = SObjectForTest.getProgram('teste');
        lPr.SiteUrl__c = '';
        insert lPr;

        Account lAcc = SObjectForTest.getAccount();

        insert lAcc;

        return [SELECT FieloPLT__Email__c, FieloPLT__User__c, FieloPLT__User__r.userName, 
                FieloPLT__Program__c, FieloPLT__Account__c
                FROM FieloPLT__Member__c 
                WHERE FieloPLT__Account__c = :lAcc.id];
    }
}