src/objects/Ter_Estacion_de_Servicio__c.object
<CustomObject>
    <description>Este objeto contiene los registros de las estaciones de servicio de Terpel asociadas a sus operadores.</description>
    <fields>
        <fullName>F_ClubTerpel__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Habilitar para el programa de Fidelización &quot;Club Terpel&quot; (Fielo)</inlineHelpText>
        <label>Club Terpel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ter_Ciudad__c</fullName>
        <description>Este campo contiene la ciudad de la estación de servicio.</description>
        <label>Ciudad</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ter_Direccion__c</fullName>
        <description>Este campo indica la dirección de la estación de servicio.</description>
        <label>Dirección</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ter_Estatus__c</fullName>
        <description>Este campo contiene el estado de la estación de servicio.</description>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activa</fullName>
                </value>
                <value>
                    <fullName>Inactiva</fullName>
                </value>
                <value>
                    <fullName>inactiva (ambiental)</fullName>
                </value>
                <value>
                    <fullName>inactiva otro</fullName>
                </value>
                <value>
                    <fullName>inactiva (juridico)</fullName>
                </value>
                <value>
                    <fullName>inactiva cupo ley frontera</fullName>
                </value>
                <value>
                    <fullName>inactiva (prob. economicos)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (pend. renov)</fullName>
                </value>
                <value>
                    <fullName>inactiva (certificación)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (orden publico)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (Extinción de dominio)</fullName>
                </value>
                <value>
                    <fullName>inactiva (muerte prop)</fullName>
                </value>
                <value>
                    <fullName>inactiva (zona contrabando)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (juridico)</fullName>
                </value>
                <value>
                    <fullName>inactiva (voluntad prop.)</fullName>
                </value>
                <value>
                    <fullName>inactiva (contraccion mercado)</fullName>
                </value>
                <value>
                    <fullName>inactiva (embargo banco-no se compro)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (prob. Economicos)</fullName>
                </value>
                <value>
                    <fullName>inactiva (orden publico)</fullName>
                </value>
                <value>
                    <fullName>inactiva (prob. vial)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (certificación)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ter_Latitud__c</fullName>
        <description>Este campo posee la latitud de la estación de servicio.</description>
        <label>Latitud</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ter_Longitud__c</fullName>
        <description>Este campo contiene la longitud geográfica de la estación de servicio.</description>
        <label>Longitud</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ter_Marca__c</fullName>
        <description>Este campo contiene la marca de la estación de servicio.</description>
        <label>Marca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Terpel</fullName>
                </value>
                <value>
                    <fullName>Esso</fullName>
                </value>
                <value>
                    <fullName>Mobil</fullName>
                </value>
                <value>
                    <fullName>Texaco</fullName>
                </value>
                <value>
                    <fullName>Petrobrás</fullName>
                </value>
                <value>
                    <fullName>Petromil</fullName>
                </value>
                <value>
                    <fullName>Brio</fullName>
                </value>
                <value>
                    <fullName>Biomax</fullName>
                </value>
                <value>
                    <fullName>Puma</fullName>
                </value>
                <value>
                    <fullName>Zeuss</fullName>
                </value>
                <value>
                    <fullName>Otra</fullName>
                </value>
                <value>
                    <fullName>Gazel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ter_Segmento__c</fullName>
        <description>Este campo contiene el segmento de la estación de servicio.</description>
        <label>Segmento</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>EDS TERCEROS</fullName>
                </value>
                <value>
                    <fullName>EDS OPESE</fullName>
                </value>
                <value>
                    <fullName>EDS FRANQUICIADAS</fullName>
                </value>
                <value>
                    <fullName>EDS PROPIAS (POD)</fullName>
                </value>
                <value>
                    <fullName>EDS PROPIAS (POT)</fullName>
                </value>
                <value>
                    <fullName>COMPETENCIA</fullName>
                </value>
                <value>
                    <fullName>COINVERSIÓN</fullName>
                </value>
                <value>
                    <fullName>CORPORATIVA</fullName>
                </value>
                <value>
                    <fullName>FRANQUICIADA</fullName>
                </value>
                <value>
                    <fullName>PROPIA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Estación de Servicio</label>
    <nameField>
        <label>Nombre EDS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estaciones de Servicio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Widget1API.cls
global with sharing class Widget1API implements FieloCMS.ViewInterface{

    public List<LocationWrapper> fLocation { get; set; }
    public String fIdEstacion { get; set; } 
    public String fEstacionDetail { get; set; } 

    public String fLocationJson { 
        get {

            if(fLocation != null && fLocation.size() > 0) {

                return JSON.serialize(fLocation);
            }
            else {
                return '';
            }
        }
        set;
    }

    public Widget1API() {

        fLocation = new List<LocationWrapper>();

        Set<Id> lEstacionSet = new Set<Id>();
        for(Ter_Estacion_de_Servicio__c es :[SELECT Name, Ter_Latitud__c, Ter_Longitud__c, Ter_Direccion__c, Ter_Ciudad__c
                                             FROM Ter_Estacion_de_Servicio__c
                                             WHERE Ter_Estatus__c = 'Activa'
                                             AND Ter_Segmento__c != 'COMPETENCIA'
                                             AND Ter_Marca__c = 'Terpel'
                                             AND F_ClubTerpel__c = TRUE
                                             AND ( Ter_Latitud__c != NULL OR Ter_Longitud__c != NULL )
                                             ]) {

            lEstacionSet.add(es.id);
            fLocation.add(new LocationWrapper(es.id, es.Name, es.Ter_Latitud__c, es.Ter_Longitud__c, es.Ter_Direccion__c, es.Ter_Ciudad__c));
        }

        Map<Id,Id> lAnexosMap = new Map<Id,Id>();
        for(Attachment att :[SELECT Id FROM Attachment WHERE ParentId IN :lEstacionSet]) {

            lAnexosMap.put(att.ParentId, att.id);
        }

        for(LocationWrapper lc :fLocation) {

            // Utiliza o campo estacionId para armazenar o id da estação, após isto
            // atuliza o campo para o id do anexo ou seta como null se não tive anexo
            Id lIdAux = lAnexosMap.get(lc.estacionId);
            if(lIdAux != null) {
                lc.estacionId = lIdAux;
            }
            else {
                lc.estacionId = null;
            }
        }

    }

    global ApexPages.Component getComponent(FieloCMS__Component__c c){                
        Component.Widget1 mapa = new Component.Widget1(config=c);

        return mapa;        
    }

    public class LocationWrapper {

        String estacionId { get; set; }
        String name { get; set; }
        Decimal latitude { get; set; }
        Decimal longitude { get; set; }
        String address { get; set; }
        String city { get; set; }

        public LocationWrapper(String aEstacionId, String aName, Decimal aLat, Decimal aLong, String aAddress, String aCity) {
            this.estacionId = aEstacionId;
            this.name = aName;
            this.latitude = aLat;
            this.longitude = aLong;
            this.address = aAddress;
            this.city = aCity;
        }
    }

    webService static String estacionDetail(String aEstacionId) {

        List<Ter_Estacion_de_Servicio__c> lEstacionLst = [
            SELECT Name, Ter_Latitud__c, Ter_Longitud__c, Ter_Direccion__c, Ter_Ciudad__c 
            FROM Ter_Estacion_de_Servicio__c
            WHERE id = :aEstacionId];

        if(lEstacionLst.size() == 0) {
            return '';
        }
        else {
            String fURLAttachment;
            List<Attachment> lAnexos = [SELECT Id FROM Attachment WHERE ParentId = :lEstacionLst[0].Id];
            if (!lAnexos.isEmpty()) {
              String lURL = ProgramService.getProgramByDomain().SiteURL__c;
              if ( lURL != null )
              {
                String[] lParts = lURL.split('/'); 
                if(lParts.size() > 1) {
                    lURL = '/' + lParts[ lParts.size()-1 ];
                }
                else {
                    lURL = '';
                }
                
              }
                fURLAttachment = lURL + '/servlet/servlet.FileDownload?file=' + lAnexos.get(0).id;
                //corpoRegulamento = EncodingUtil.base64Encode(lAnexos.get(0).Body);
            } 

            String lResult = '<div id="content">' +
                '<div id="siteNotice">' +
                '</div>' +
                '<h1 id="firstHeading" class="firstHeading">' + lEstacionLst[0].Name + '</h1>' +
                '<div id="bodyContent">' +
                '<p><b>Estación: ' + lEstacionLst[0].Name + '</b>.</p>';

            if(String.isNotEmpty(fURLAttachment)) {

                lResult += '<p>Image: <apex:image url="' + fURLAttachment + '"/></p>';
            }
                
            lResult += '</div></div>';

            return lResult;
        }
    }
}