src/objects/Ter_Estacion_de_Servicio__c.object
<CustomObject>
    <description>Este objeto contiene los registros de las estaciones de servicio de Terpel asociadas a sus operadores.</description>
    <fields>
        <fullName>F_ClubTerpel__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Habilitar para el programa de Fidelización &quot;Club Terpel&quot; (Fielo)</inlineHelpText>
        <label>Club Terpel</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>F_IdFidelizacion__c</fullName>
        <externalId>true</externalId>
        <label>Id Fidelizacion</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Ter_Estatus__c</fullName>
        <description>Este campo contiene el estado de la estación de servicio.</description>
        <label>Estatus</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Activa</fullName>
                </value>
                <value>
                    <fullName>Inactiva</fullName>
                </value>
                <value>
                    <fullName>inactiva (ambiental)</fullName>
                </value>
                <value>
                    <fullName>inactiva otro</fullName>
                </value>
                <value>
                    <fullName>inactiva (juridico)</fullName>
                </value>
                <value>
                    <fullName>inactiva cupo ley frontera</fullName>
                </value>
                <value>
                    <fullName>inactiva (prob. economicos)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (pend. renov)</fullName>
                </value>
                <value>
                    <fullName>inactiva (certificación)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (orden publico)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (Extinción de dominio)</fullName>
                </value>
                <value>
                    <fullName>inactiva (muerte prop)</fullName>
                </value>
                <value>
                    <fullName>inactiva (zona contrabando)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (juridico)</fullName>
                </value>
                <value>
                    <fullName>inactiva (voluntad prop.)</fullName>
                </value>
                <value>
                    <fullName>inactiva (contraccion mercado)</fullName>
                </value>
                <value>
                    <fullName>inactiva (embargo banco-no se compro)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (prob. Economicos)</fullName>
                </value>
                <value>
                    <fullName>inactiva (orden publico)</fullName>
                </value>
                <value>
                    <fullName>inactiva (prob. vial)</fullName>
                </value>
                <value>
                    <fullName>inactiva sin contrato (certificación)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Ter_Latitud__c</fullName>
        <description>Este campo posee la latitud de la estación de servicio.</description>
        <label>Latitud</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ter_Longitud__c</fullName>
        <description>Este campo contiene la longitud geográfica de la estación de servicio.</description>
        <label>Longitud</label>
        <precision>10</precision>
        <scale>6</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ter_Marca__c</fullName>
        <description>Este campo contiene la marca de la estación de servicio.</description>
        <label>Marca</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Terpel</fullName>
                </value>
                <value>
                    <fullName>Esso</fullName>
                </value>
                <value>
                    <fullName>Mobil</fullName>
                </value>
                <value>
                    <fullName>Texaco</fullName>
                </value>
                <value>
                    <fullName>Petrobrás</fullName>
                </value>
                <value>
                    <fullName>Petromil</fullName>
                </value>
                <value>
                    <fullName>Brio</fullName>
                </value>
                <value>
                    <fullName>Biomax</fullName>
                </value>
                <value>
                    <fullName>Puma</fullName>
                </value>
                <value>
                    <fullName>Zeuss</fullName>
                </value>
                <value>
                    <fullName>Otra</fullName>
                </value>
                <value>
                    <fullName>Gazel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Estación de Servicio</label>
    <nameField>
        <label>Nombre EDS</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estaciones de Servicio</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Widget1APITest.cls
/*******************************************************************************
*                          Copyright (C) 2017 ValueNET
* ------------------------------------------------------------------------------
* Author: JNS                          date: 03/08/2017
* 
* Name: Widget1APITest.trigger
* 
* Classe de teste do controller Widget1API.cls
*
*******************************************************************************/
@isTest
private class Widget1APITest
{
	@isTest
	static void itShould()
	{
		FieloPLT__Member__c LMemberCliente =  createMemberByAccount();
		Ter_Estacion_de_Servicio__c lEstacionServ = SObjectForTest.getEstacionDeServicio();
		lEstacionServ.Ter_Longitud__c = 1;
		lEstacionServ.Ter_Latitud__c = 1;
		lEstacionServ.F_IdFidelizacion__c = LMemberCliente.id;
        lEstacionServ.Ter_Estatus__c = 'Activa';
        lEstacionServ.Ter_Marca__c = 'Terpel';
        lEstacionServ.F_ClubTerpel__c = TRUE;
		insert lEstacionServ;

		Test.startTest();	

		system.runAs(LMemberCliente.FieloPLT__User__r) {

			Widget1API lTela = new Widget1API();
			Widget1API.estacionDetail(lEstacionServ.id);
			String lTest = lTela.fLocationJson + lTela.fIdEstacion  + lTela.fEstacionDetail;

		}
		Test.stopTest();

	}

	private static FieloPLT__Member__c createMemberByAccount() {

		FieloPLT__Program__c lPr = SObjectForTest.getProgram('teste');
		lPr.SiteUrl__c = '';
		insert lPr;

		Account lAcc = SObjectForTest.getAccount();

		insert lAcc;

		return [SELECT FieloPLT__Email__c, FieloPLT__User__c, FieloPLT__User__r.userName
				FROM FieloPLT__Member__c 
				WHERE FieloPLT__Account__c = :lAcc.id];
	}
}